# Generated by Django 4.2.1 on 2023-06-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0003_booking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={"verbose_name_plural": "services"},
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="mobile",
            new_name="phone_number",
        ),
    ]
