# Generated by Django 4.2.1 on 2023-06-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0004_alter_services_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="services",
            name="thumbnail_image",
            field=models.ImageField(blank=True, null=True, upload_to="services"),
        ),
    ]
