# Generated by Django 4.1.6 on 2023-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0006_alter_booking_booking_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_type',
            field=models.IntegerField(default=0),
        ),
    ]
