# Generated by Django 4.1.6 on 2023-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0007_booking_pickup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='journey_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_journey_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_journey_time',
            field=models.DateField(null=True),
        ),
    ]
