# Generated by Django 4.1.6 on 2023-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0010_alter_booking_journey_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='journey_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_journey_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
    ]
