# Generated by Django 4.1.6 on 2023-06-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0012_alter_booking_flight_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='journey_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_journey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_journey_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
