# Generated by Django 4.1.6 on 2023-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_car', '0013_alter_booking_journey_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_return_journey',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='privacy_agree',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='terms_agree',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
