# Generated by Django 4.2.1 on 2023-06-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0015_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="pickup_type",
            field=models.CharField(
                choices=[
                    ("Airport", "Airport"),
                    ("Railway", "Railway"),
                    ("Seaport", "Seaport"),
                    ("Other address", "Other address"),
                ],
                default="Airport",
                max_length=20,
            ),
        ),
    ]
