# Generated by Django 4.2.1 on 2023-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0016_alter_booking_pickup_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("pay in the car by card", "pay in the car by card"),
                    ("Pay in advance", "Pay in advance"),
                ],
                default="Cash",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_type",
            field=models.CharField(
                choices=[
                    ("Airport", "Airport"),
                    ("Railway", "Railway"),
                    ("Seaport", "Seaport"),
                    ("Other address", "Other address"),
                ],
                default="Airport",
                max_length=30,
            ),
        ),
    ]
