# Generated by Django 4.2.1 on 2023-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0017_alter_booking_payment_type_alter_booking_pickup_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                ("content", models.TextField()),
                ("rating", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_published",
                    models.BooleanField(
                        choices=[("Pending", "Pending"), ("Active", "Active")],
                        default=False,
                    ),
                ),
            ],
        ),
    ]
