# Generated by Django 4.2.1 on 2023-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0018_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.EmailField(blank=True, max_length=155, null=True),
        ),
    ]
