# Generated by Django 4.2.1 on 2023-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0019_review_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Active", "Active")],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
