# Generated by Django 4.2.1 on 2023-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_car", "0020_alter_review_options_review_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
